export NODE22_VERSION=22.22.3
export NODE24_VERSION=24.16.0
# Nginx version
export NGINX_VERSION=1.30.2
# Supervisor version
export SUPERVISOR_VERSION=4.2.5
# Browsers
export CHROME_VERSION=148.0.7778.178
export FIREFOX_VERSION=151.0.2
