export NODE22_VERSION=22.23.2
export NODE24_VERSION=24.21.0
# Nginx version
export NGINX_VERSION=1.30.5
# Supervisor version
export SUPERVISOR_VERSION=4.2.5
# Browsers
export CHROME_VERSION=153.0.8010.52
export FIREFOX_VERSION=156.0
