export NODE22_VERSION=22.22.0
export NODE24_VERSION=24.13.0
# Nginx version
export NGINX_VERSION=1.28.1
# Supervisor version
export SUPERVISOR_VERSION=4.2.5
# Browsers
export CHROME_VERSION=144.0.7559.109
export FIREFOX_VERSION=147.0.2
