# Docker
# Build and push php images to Docker Hub
name: Build and push

on:
  push:
    paths:
      - 'build/**'
      - '.github/**'
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  node20-base:
    name: Build and push node20 base image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./build/node20/base
          file: ./build/node20/base/Dockerfile
          cache-from: type=gha,scope=node20
          cache-to: type=gha,scope=node20,mode=max
          push: true
          tags: anzusystems/node:${{ github.ref_name }}-node20,anzusystems/node:latest-node20

  node20-nginx:
    name: Build and push node20 nginx image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./build/node20/nginx
          file: ./build/node20/nginx/Dockerfile
          cache-from: type=gha,scope=node20-nginx
          cache-to: type=gha,scope=node20-nginx,mode=max
          push: true
          tags: anzusystems/node:${{ github.ref_name }}-node20-nginx,anzusystems/node:latest-node20-nginx

  node20-nginx-browsers:
    name: Build and push node20 nginx-browsers image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./build/node20/nginx-browsers
          file: ./build/node20/nginx-browsers/Dockerfile
          cache-from: type=gha,scope=node20-nginx-browsers
          cache-to: type=gha,scope=node20-nginx-browsers,mode=max
          push: true
          tags: anzusystems/node:${{ github.ref_name }}-node20-nginx-browsers,anzusystems/node:latest-node20-nginx-browsers

